name: Run Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run JSON script
        id: json_script
        run: python json_script.py
      - name: Execute Script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            print(${{ fromJSON(steps.json_script.outputs) }})
